### ISSUE TITLE
unable to run app

### ISSUE THREAD

**Issue by RavanaAbhi** [joelkanyi/NewsApp#1]
e: E:\GitHubProjects\NewsApp-master\NewsApp-master\app\build.gradle.kts:25:58: Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public val TaskContainer.properties: TaskProvider<PropertyReportTask> defined in org.gradle.kotlin.dsl

>> Ask Gemini Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
public val TaskContainer.properties: TaskProvider<PropertyReportTask> defined in org.gradle.kotlin.dsl

**Comment by joelkanyi** [comment]
Hey @RavanaAbhi did you create `local.properties` on your clone?

**Comment by RavanaAbhi** [comment]
yes
sdk.dir=C\:\\Users\\Abhi\\AppData\\Local\\Android\\Sdk

**Comment by joelkanyi** [comment]
You also need to add your API key in the `local.properties`

```gradle
sdk.dir=C:\Users\Abhi\AppData\Local\Android\Sdk
API_KEY=YOUR_API
```
